contact_links:
  - name: Discord
    url: https://discord.gg/flirtual
    about: Join our Discord community for feature requests, help, developer discussion, and more
  - name: Support
    url: https://hello.flirtu.al
    about: Contact us for help with your account
  - name: Changelog
    url: https://flirtu.al/news
    about: See our latest updates
