# fly.toml app configuration file generated for image-classification on 2023-06-10T14:13:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "image-classification"
primary_region = "ord"
